baseURL = "https://main--magenta-narwhal-7d1776.netlify.app/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "browerybychean"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Testimonials"
url = "#testimonial"
weight = 4
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "Instagram"
url = "https://www.instagram.com/browerybychean"
weight = 1
[[menu.sitemap]]
name = "Facebook"
url = "https://www.facebook.com/Browerybychean/"
weight = 2
[[menu.sitemap]]
name = "WhatsApp"
url = "https://wa.me/601115133113"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/site-navigation/BBC3.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/BBC2.png"

[params.address]
address = "Based in Penang, Serving Across Malaysia."
email = "hello@browerybychean.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+601115133113"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/Browerybychean/"
weight = 1
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/browerybychean"
weight = 2
[[params.social]]
icon = "fa-whatsapp"
url = "https://wa.me/601115133113"
weight = 3